name = "SpaceDataModel"
uuid = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
version = "0.2.8"
authors = ["Zijin Zhang <zzj956959688@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[extensions]
SpaceDataModelCommonDataModelExt = "CommonDataModel"
SpaceDataModelDimensionalDataExt = "DimensionalData"

[compat]
CommonDataModel = "0.4"
ConstructionBase = "1"
Dates = "1"
DimensionalData = "0.29, 0.30"
julia = "1.10"
